name: Snake Contributions

on:
  workflow_dispatch:   # Run manually from Actions tab

jobs:
  create-snake-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # Disable default token to use PAT later

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create snake commits
        run: |
          START_DATE="2024-07-28"
          SNAKE_CELLS=(
            "0 3" "1 3" "2 3" "3 3" "4 3" "5 3" "6 3" "7 3" "8 3" "9 3"
            "9 4" "8 4" "7 4" "6 4" "5 4" "4 4" "3 4" "2 4" "1 4" "0 4"
          )
          for cell in "${SNAKE_CELLS[@]}"; do
            week=$(echo $cell | cut -d' ' -f1)
            day=$(echo $cell | cut -d' ' -f2)
            commit_date=$(date -d "$START_DATE +$week week +$day day" +"%Y-%m-%d")
            echo "Creating commit for $commit_date"
            GIT_AUTHOR_DATE="$commit_date 12:00:00" GIT_COMMITTER_DATE="$commit_date 12:00:00" \
            git commit --allow-empty -m "Snake commit on $commit_date"
          done

      - name: Push commits
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
